apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakEyTURneQpNRFU0TUROYUZ3MDBNakEyTURneU1EVTRNRE5hTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFERVFsYjBJdDdoMWExdkgrakRDVXJYbUNkQ0VvcHVQeWl5bWExSXg5U25UMWNkeXRDdgpTUXpickJrcEIyNUFIeVU4ay81dnI2Qi8yNFR3TTBZd1NSWFhJTk9udXRFNU5ieXd4NjNJN0Uvc3NaejVKdHErCkVIbE1tM1NCeWFqMktyQjVSWUp3ajVsRHQ1SEFRQldZREIyUVZMYXlmcGl3SmltQlMrRFhnZzRGYVNPTzNISFUKd3ZPZmdoc0dtMWdHeDA5ejlDK0h0VGhmY2dQU0srRnZob01aK2FPdEhKOTNqRUNLL2tBMHlNNUdPYWN0OFFXUwo2RUg5N1VZTHJucmoxNUZoTFg5U1lsMVZsYzhFREl4THVRSGtweGl1MmhURUJySlZHcWc2bjFWczhWRzB5blhHCnB0ZUl3WVB4VGdhZllYTTZzWVU0WTIvQmhnb0NTejNVYWdScEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlJLcGo1ZHVVc0EyN1huQi96MAo2N1ltQ3dCSU9qQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFJQjJock1EUm56WU9oQmx2MEh4eXF5Ti9PR1F3CnUwMXg5SWVRbVNGbitCRHpYSVpxWjBuUTJTZVBpVWs3bW9nOUMvMlV1VmE5ODI5UitLNjk0R3piNjNjdFJCbTIKK1VIUTRrb0RmK3N6dFBCVWxHZjJOV2ZEYmlreHRud3Q2b3gxUFdVbEFzY0xiWWdwK0FDTHoxMlRBSG5GMG44SQpiL3NhelgrMUlVaFE1ZFU4LzFDUVl2YmM0OGFVK084aG9ScVJUeWRTd0RMaEhNVXF0Y05CVVBxNzVvNnBWc1o3ClZ6OXY3a2twRVk4REZlcExhYUpJZnJNVkk2Rlk3VXBlc1MzSTd3Ykl3ZCtQQzJ3WEQwa0xEMUlVTnM0OFlINmgKOGZSRGlkY1ZnL0hqUmhyTmo2WFFCc3lkUjNRZkRHaStQdmhLejA2Q1ZRTFE5ejNiYlFFMmx4K3NXQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://8099a12a-92f4-4f33-be33-734d8fb12e93.k8s.ondigitalocean.com
  name: do-nyc1-k8s-iniciativa
contexts:
- context:
    cluster: do-nyc1-k8s-iniciativa
    user: do-nyc1-k8s-iniciativa-admin
  name: do-nyc1-k8s-iniciativa
current-context: do-nyc1-k8s-iniciativa
kind: Config
preferences: {}
users:
- name: do-nyc1-k8s-iniciativa-admin
  user:
    token: dop_v1_989cd3aff15cd9a133da4c0d4972a98f891ae526eacd3fa0b803ba76ce311ca9
